[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[build]
target = [
  "x86_64-unknown-linux-musl",
  "x86_64-pc-windows-msvc",
  "aarch64-unknown-linux-musl",
  "aarch64-unknown-darwin-musl",
]
