package:
  version: 0.0.11
  name: pyxis-py
build:
  number: 0
  script:
    pwsh -f %RECIPE_DIR%\build-pyxis-py.ps1
requirements:
  host:
    - python
    - pip

  run:
    - lazy-loader
    - numpy
    - scipy
    - pyproj

tests:
  - python:
      imports:
        - pyxis 
