codecov:
  token: 63801301-7a53-44db-86aa-be640d53e98a
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment:
  behavior: default
ignore:
  - "crates/pyxis-py/src"
