version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - /.github/workflows
      - /.github/actions/setup-ci

    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  - package-ecosystem: cargo
    directory: ./src/rust
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    groups:
      dependencies:
        patterns:
          - "*"
