version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - .github/workflows
      - .github/actions/setup-ci
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"

  - package-ecosystem: cargo
    directories:
      - ./rust
      - ./python
    schedule:
      interval: monthly
    commit-message:
      prefix: build
    groups:
      dependencies:
        patterns:
          - "*"
