name: Setup CI
outputs:
  py: 
    value: ${{steps.py.outputs.any_changed}}
  rs: 
    value: ${{steps.rs.outputs.any_changed}}
  cpp: 
    value: ${{steps.cpp.outputs.any_changed}}
  cuda: 
    value: ${{steps.cuda.outputs.any_changed}}
runs:
  using: "composite"
  steps:
    - id: py
      uses: tj-actions/changed-files@v45
      with:
        files: |
          src/**.py
          pixi.toml
          pixi.lock
          **/ruff.toml

    - id: rs
      uses: tj-actions/changed-files@v45
      with:
        files: |
          src/rust/*
    
    - id: cpp
      uses: tj-actions/changed-files@v45
      with:
        files: |
          src/cpp/*

    - id: cuda
      uses: tj-actions/changed-files@v45
      with:
        files: |
          src/cuda/*

