name: Setup CI
runs:
  using: "composite"
  outputs:
    py: ${{steps.py.outputs.any_changed}}
    rs: ${{steps.rs.outputs.any_changed}}
    cpp: ${{steps.cpp.outputs.any_changed}}
    cuda: ${{steps.cuda.outputs.any_changed}}

  steps:
    - id: py
      uses: tj-actions/changed-files@v45
      with:
        files: |
          src/**.py
          pixi.toml
          pixi.lock
          **/ruff.toml

    - id: rs
      uses: tj-actions/changed-files@v45
      with:
        files: |
          src/rust/*
    
    - id: cpp
      uses: tj-actions/changed-files@v45
      with:
        files: |
          src/cpp/*

    - id: cuda
      uses: tj-actions/changed-files@v45
      with:
        files: |
          src/cuda/*

