[project]
authors = ["Glatzel <893016099@qq.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "rs-geotool"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[feature.py311.dependencies]
python = "3.11.*"

[feature.build.dependencies]
maturin = "*"
pip = "*"
pkg-config = "*"

[feature.py-deps.dependencies]
numpy = "*"
scipy="*"
nomkl = "*"
lazy-loader = "*"

[feature.py-test.dependencies]
pytest = "*"
pytest-cov = "*"

[feature.py-doc.dependencies]
sphinx = "*"
pydata-sphinx-theme = "*"
sphinx-copybutton = "*"
numpydoc = "*"
autodocsumm = "*"
sphinx-autosummary-accessors = "*"

[environments]
default=["py311","build","check","py-deps","py-test","py-doc"]
ci-cli=["build"]
ci-py=["py311","build","py-deps","py-test","py-doc"]