name: Setup CI
runs:
  using: "composite"
  steps:
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        run-install: false

    - name: restore vcpkg
      if: ${{ runner.os == 'Windows' }}
      uses: actions/cache/restore@v4
      with:
        path: ./vcpkg/installed
        key: vcpkg-${{ runner.os }}-${{ hashFiles('./vcpkg/vcpkg.json') }}
