package:
  version: 0.0.34
  name: pyxis-cuda
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%/build-pyxis-cuda.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-pyxis-cuda.ps1
