package:
  version: 0.0.37
  name: pyxis-py
build:
  number: 0

  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%/build-pyxis-py.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-pyxis-py.ps1

requirements:
  host:
    - python 3.11.*
    - pip
  run:
    - python >= 3.11
    - lazy-loader
    - numpy
    - scipy

tests:
  - python:
      imports:
        - pyxis
