[package]
edition.workspace = true
name = "pyxis-abacus"
version.workspace = true

[[bin]]
name = "pyxis"
path = "src/main.rs"

[dependencies]
bpaf = { workspace = true }
miette = { workspace = true }
proj = { workspace = true }
pyxis = { workspace = true, features = ["serde", "log"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap-verbosity-flag = { workspace = true }
clerk = { workspace = true, features = ["log", "serde"] }
crossterm = { workspace = true }
directories = { workspace = true }
ratatui = { workspace = true }
rax = { workspace = true, features = ["async"] }
rax-nmea = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
tokio-serial = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
float-cmp = { workspace = true }
predicates = { workspace = true }
async-trait = { workspace = true }
tempfile = { workspace = true }
