package:
  version: 0.0.34
  name: pyxis-abacus
build:
  number: 0
  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%/build-pyxis-cli.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-pyxis-cli.ps1
tests:
  - script:
      - if: win
        then:
          - "%PREFIX%/pyxis/bin/pyxis-abacus.exe --help"
      - if: unix
        then:
          - "$PREFIX/pyxis/bin/pyxis-abacus --help"
