context:
  version: 1.37.0
package:
  version: ${{ version }}
  name: aria2
build:
  number: 2
  script:
  - if: win
    then:
    - pwsh -f %RECIPE_DIR%\build-pyxis-cli.ps1
tests:
- script:
  - if: win
    then:
      '%PREFIX%/bin/pyxis-cli/pyxis.exe --help'
