[package]
name = "pyxis-py"
version.workspace = true
edition.workspace = true

[dependencies]
numpy = { workspace = true }
pyo3 = { workspace = true }
pyxis = { workspace = true }
rayon = { workspace = true }
miette = { workspace = true }

[lib]
name = "pyxis_py"
crate-type = ["cdylib"]
