[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "pyxis"
requires-python = ">=3.11"
dynamic = ["version"]
authors = [{ name = "Glatzel", email = "893016099@qq.com" }]
dependencies = ["lazy-loader", "numpy", "scipy"]

[project.optional-dependencies]
gpu = ["cupy"]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "pyxis.pyxis_py"

[tool.numpydoc_validation]
checks = [
    "all",  # report on all checks, except the below
    "ES01", # No extended summary found
    "EX01", # No examples section found
    "GL08", # The object does not have a docstring
    "PR04", # Parameter "{param_name}" has no type
    "RT03", # Return value has no description
    "SA01", # See Also section not found
    "SA04", # Missing description for See Also "{reference_name}" reference
]
