[package]
edition.workspace = true
name = "proj-sys"
version.workspace = true

[build-dependencies]
bindgen = { workspace = true, optional = true }
clerk = { workspace = true, features = ["log"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
pkg-config = { workspace = true }

[dependencies]
libc = { workspace = true }

[features]
bindgen = ["dep:bindgen"]
update = []