[package]
edition.workspace = true
name = "proj-sys"
version = "9.7.0"

[dependencies]
libc = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }
pkg-config = { workspace = true }
