[package]
edition.workspace = true
name = "proj-sys"
version.workspace = true

[build-dependencies]
bindgen = { workspace = true, optional = true }
pkg-config = { workspace = true }

[features]
bindgen = ["dep:bindgen"]
update = []
