[workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[dependencies]
lazy-loader = "==0.4"
pip = "==25.1.1"
python = "3.11.*"
rattler-build = "==0.42.1"

[feature.test.dependencies]
cupy = "==13.4.1"
nomkl = "==1.0"
pytest = "==8.3.5"
pytest-benchmark = "==5.1.0"
pytest-cov = "==6.1.1"
[feature.test.target.linux-64.dependencies]
cuda-runtime = "==12.8.1"

[environments]
test = ["test"]
