[workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[dependencies]
lazy-loader = "==0.4"
pip = "==25.2"
python = "3.11.*"
rattler-build = "==0.46.0"

[feature.test.dependencies]
cupy = "==13.6.0"
nomkl = "==1.0"
pytest = "==8.4.1"
pytest-benchmark = "==5.1.0"
pytest-cov = "==6.2.1"

[environments]
test = ["test"]
