[workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[dependencies]
lazy-loader = "==0.4"
pip = "==25.1.1"
python = "3.11.*"
rattler-build = "==0.42.1"

[feature.local-test.dependencies]
cupy = "==13.4.1"
pytest = "==8.3.5"
pytest-benchmark = "==5.1.0"
pytest-cov = "==6.1.1"

[environments]
local-test = ["local-test"]
