package:
  version: 0.0.31
  name: pyxis-py-cuda
build:
  number: 0
  string: ${{ 'core' if cuda_variant=='cupy-core' else 'full'}}_${{ hash }}_${{ build_number }}

  script:
    - if: win
      then:
        - pwsh -f %RECIPE_DIR%/build-pyxis-cuda-py.ps1
    - if: unix
      then:
        - pwsh -f $RECIPE_DIR/build-pyxis-cuda-py.ps1

requirements:
  host:
    - python 3.11.*
    - pip
  run:
    - python >= 3.11
    - lazy-loader
    - ${{cuda_variant}}
