name: Setup CI Windows
outputs:
  rust-cache-hit:
    value: ${{ steps.restore-rust.outputs.cache-hit }}
  rust-cache-primary-key:
    value: ${{steps.restore-rust.outputs.cache-primary-key}}
runs:
  using: "composite"
  steps:
    - name: set pkg-config path
      run: echo ${{github.workspace}}\.pixi\envs\dev\Library\bin >> $env:GITHUB_PATH
      shell: pwsh

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        run-install: false

    - name: restore pixi
      uses: actions/cache/restore@v4
      with:
        path: .pixi
        key: pixi-${{ runner.os }}-${{ hashFiles('**/pixi.lock') }}
    
    - name: restore vcpkg
      uses: actions/cache/restore@v4
      with:
        path: ./vcpkg_deps/vcpkg_installed
        key: vcpkg-${{ runner.os }}-${{ hashFiles('./vcpkg_dep/vcpkg.json') }}

    - name: install vcpkg dependencies
      if: ${{ github.event_name!='pull_request'}}
      run: ./scripts/install-vcpkg-dep.ps1
      shell: pwsh

    - name: restore rust
      id: restore-rust
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo
          ./target
        key: rust-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}

