[workspace]
members = ["./crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.0.35"

[workspace.dependencies]
proj = { path = "./crates/proj" }
proj-sys = { path = "./crates/proj-sys" }
pyxis = { path = "./crates/pyxis" }

clerk = { git = "https://github.com/Glatzel/toolbox", tag = "v0.0.30" }
envoy = { git = "https://github.com/Glatzel/toolbox", tag = "v0.0.30" }
rax = { git = "https://github.com/Glatzel/toolbox", tag = "v0.0.30" }
rax-nmea = { git = "https://github.com/Glatzel/toolbox", tag = "v0.0.30" }
mischief = { git = "https://github.com/Glatzel/toolbox", tag = "v0.0.30" }
serialport-ext = { git = "https://github.com/Glatzel/toolbox", tag = "v0.0.30" }

assert_cmd = "2.0"
async-trait = "0.1"
bindgen = "0.72"
bpaf = { version = "0.9.20", features = ["derive", "batteries"] }
chrono = "0.4.42"
criterion = { package = "codspeed-criterion-compat", version = "3.0.0" }
crossterm = "0.29.0"
directories = "6.0.0"
dunce = "1.0.5"
float-cmp = "0.10.0"
jsonschema = "0.33"
libc = "0.2"
num-traits = "0.2.19"
num_enum = "0.7.4"
parking_lot = { version = "0.12.4", features = ["deadlock_detection"] }
pkg-config = "0.3.32"
predicates = "3.1"
rand = "0.9.2"
ratatui = "0.29.0"
schemars = "1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
strum = { version = "0.27", features = ["derive"] }
tempfile = "3.21.0"
tokio = { version = "1", default-features = false }
tokio-serial = "5.4.5"
toml = "0.9"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3
strip = true
