[workspace]
members = ["./crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.0.30"

[workspace.dependencies]
proj = { path = "./crates/proj" }
proj-sys = { path = "./crates/proj-sys" }
pyxis = { path = "./crates/pyxis" }

assert_cmd = "2.0"
bindgen = "0.71"
bpaf = { version = "0.9.20", features = ["derive", "batteries"] }
clerk = { git = "https://github.com/Glatzel/toolbox", tag = "v0.0.22" }
criterion = { package = "codspeed-criterion-compat", version = "2.10.1" }
dunce = "1.0.5"
envoy = { git = "https://github.com/Glatzel/toolbox", tag = "v0.0.22" }
float-cmp = "0.10.0"
libc = "0.2"
miette = { version = "7.6.0", features = ["fancy"] }
num-traits = "0.2.19"
num_enum = "0.7.4"
pkg-config = "0.3.32"
predicates = "3.1"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum = { version = "0.27", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3
strip = true

[profile.develop]
inherits = "dev"
