[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"
pre-build = [
  # Let apt know we’re grabbing ARM-64 packages
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  # Install the dev package (brings in libutil, librt, pthread, etc. for arm64)
  "apt-get update",
  "apt-get install --assume-yes libudev-dev:$CROSS_DEB_ARCH libc6-dev:$CROSS_DEB_ARCH gcc-aarch64-linux-gnu g++-aarch64-linux-gnu",
  "curl -fsSL https://pixi.sh/install.sh | sh",
  "~/.pixi/bin/pixi global install proj -c https://repo.prefix.dev/glatzel --platform linux-aarch64",
  "ls -l /root/.pixi/envs/proj/proj/arm64-linux-release/lib/pkgconfig || echo 'pkgconfig not found!'",
  "export PKG_CONFIG_PATH='/root/.pixi/envs/proj/proj/arm64-linux-release/lib/pkgconfig:/usr/lib/aarch64-linux-gnu/pkgconfig'",
  "pkg-config --modversion proj",
]
[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  "PKG_CONFIG_PATH=/root/.pixi/envs/proj/proj/arm64-linux-release/lib/pkgconfig:/usr/lib/aarch64-linux-gnu/pkgconfig",
  "PKG_CONFIG_ALLOW_CROSS=1",
]
