[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"
pre-build = [
  "apt-get update",
  "apt-get install -y git build-essential cmake libsqlite3-dev libtiff-dev pkg-config curl",
  # clone and build PROJ
  "git clone --depth 1 https://github.com/OSGeo/PROJ.git /tmp/proj",
  "mkdir -p /tmp/proj/build",
  "cd /tmp/proj/build && cmake .. -DCMAKE_INSTALL_PREFIX=/opt/proj -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release",
  "cmake --build /tmp/proj/build --target install -- -j$(nproc)",
  # check installed .pc
  "ls /opt/proj/lib/pkgconfig",
]
[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  "PKG_CONFIG_PATH=/opt/proj/lib/pkgconfig",
  "PKG_CONFIG_ALLOW_CROSS=1",
]
