[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"
pre-build = [
  # Install dependencies for building proj
  "apt-get update",
  "apt-get install --assume-yes curl git build-essential cmake pkg-config",

  # Install vcpkg
  "git clone https://github.com/microsoft/vcpkg.git /vcpkg",
  "cd /vcpkg && ./bootstrap-vcpkg.sh",

  # Use vcpkg to install proj for aarch64
  "cd /vcpkg && ./vcpkg install proj --triplet aarch64-linux",

  # Set PKG_CONFIG_PATH to vcpkg's pkgconfig directory
  "export PKG_CONFIG_PATH=/vcpkg/installed/aarch64-linux/lib/pkgconfig:$PKG_CONFIG_PATH",
  
  # Check if proj is installed
  "pkg-config --modversion proj",
]

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
  "PKG_CONFIG_PATH=/vcpkg/installed/aarch64-linux/lib/pkgconfig:/usr/lib/aarch64-linux-gnu/pkgconfig",
  "PKG_CONFIG_ALLOW_CROSS=1",
]