fn_single_line = true
group_imports = "StdExternalCrate"
ignore = ["crates/proj-sys/src/bindings.rs"]
imports_granularity = "Module"
reorder_imports = true
wrap_comments = true
overflow_delimited_expr = true
