[package]
name = "pyxis"
version.workspace = true
edition.workspace = true

[[bench]]
harness = false
name = "crypto"

[[bench]]
harness = false
name = "datum_compensate"

[dependencies]
num-traits.workspace = true
serde = { workspace = true, optional = true }

[dev-dependencies]
criterion.workspace = true
float-cmp.workspace = true
insta.workspace = true
proptest.workspace = true
rstest.workspace = true

[features]
serde = ["dep:serde"]
