[workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "linux-aarch64"]

[feature.py313.dependencies]
python = "3.13.*"

[feature.build.dependencies]
maturin = "==1.12.6"
pip = "==25.3"

[feature.deps.dependencies]
lazy-loader = "==0.5"
nomkl = "==1.0"
numpy = "2.3.*"
scipy = "==1.17.1"

[feature.test.dependencies]
pytest = "==9.0.2"
pytest-cov = "==7.1.0"

[feature.bench]
platforms = ["linux-64"]
[feature.bench.dependencies]
numba = "==0.64.0"
numexpr = "==2.14.1"
pytest-codspeed = "==4.3.0"

[environments]
bench = ["py313", "build", "test", "deps", "bench"]
default = ["py313", "build", "deps", "test"]
