[package]
name = "geotool-algorithm"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
float-cmp = { workspace = true }
criterion = { workspace = true }

[features]
serde = ["dep:serde"]
log = ["dep:tracing"]

[[bench]]
name = "datum_compense"
harness = false

[[bench]]
name = "crypto"
harness = false