name: Setup CI Windows
runs:
  using: "composite"
  steps:
    - name: restore vcpkg
      uses: actions/cache/restore@v4
      with:
        path: ./vcpkg_deps/vcpkg_installed
        key: vcpkg-${{ runner.os }}-${{ hashFiles('./vcpkg_deps/vcpkg.json') }}
