[package]
edition.workspace = true
name = "proj"
version.workspace = true

[dependencies]
proj-sys = { workspace = true}
clerk = { workspace = true }
miette={ workspace = true }

[features]
log = ["clerk/log"]