[package]
edition.workspace = true
name = "proj"
version.workspace = true

[dependencies]
proj-sys = { workspace = true,features = ["bindgen"]}
clerk = { workspace = true }
miette={ workspace = true }

[dev-dependencies]
float-cmp = { workspace = true }

[features]
log = ["clerk/log"]
