[package]
edition.workspace = true
name = "proj"
version.workspace = true

[dependencies]
clerk = { workspace = true }
miette = { workspace = true }
serde = { workspace = true, optional = true }
proj-sys = { workspace = true }

[dev-dependencies]
clerk = { workspace = true, features = ["log"] }
float-cmp = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
log = ["clerk/log"]
serde = ["dep:serde","proj-sys/serde"]
unrecommended = []
