[package]
edition.workspace = true
name = "proj"
version.workspace = true

[dependencies]
proj-sys = { workspace = true}
clerk = { workspace = true }
miette={ workspace = true }

[dev-dependencies]
float-cmp = { workspace = true }

[features]
log = ["clerk/log"]
# proj features
full=["distances","info","iso19111","lists","network","various","unsuggested"]
distances=[]
info=[]
iso19111=[]
lists=[]
network=[]
various=[]

unsuggested=[]
