[package]
name = "py-geotool"
version.workspace = true
edition.workspace = true

[dependencies]
pyo3 = { workspace = true }
ndarray ={ workspace = true }
numpy={ workspace = true }
geotool-algorithm={ workspace = true }
rayon={ workspace = true }

[lib]
name = "py_geotool"
crate-type = ["cdylib"]