[package]
name = "gnss-receiver"
version = "0.0.44"
edition = "2024"

[[bin]]
name = "gnss-receiver"
path = "src/main.rs"

[[bin]]
name = "deadlock_detection"
path = "tools/deadlock_detection.rs"

[[bin]]
name = "export-schema"
path = "tools/export_schema.rs"

[[bin]]
name = "list-devices"
path = "tools/list_devices.rs"

[dependencies]
clerk = { git = "https://github.com/Glatzel/toolbox", tag = "v2026.7.27", features = [
  "tracing"
] }
mischief = { git = "https://github.com/Glatzel/toolbox", tag = "v2026.7.27", features = [
  "fancy"
] }
rax = { git = "https://github.com/Glatzel/toolbox", tag = "v2026.7.27", features = [
  "async"
] }
rax-nmea = { git = "https://github.com/Glatzel/toolbox", tag = "v2026.7.27" }
serialport-ext = { git = "https://github.com/Glatzel/toolbox", tag = "v2026.7.27" }

proj = { path = "../../rust/crates/proj" }
pyxis = { path = "../../rust/crates/pyxis", features = ["serde"] }

bpaf = { version = "0.9.27", features = ["batteries", "derive"] }
chrono = "0.4.45"
crossterm = "0.29.0"
directories = "6.0.0"
parking_lot = { version = "0.12.5", features = ["deadlock_detection"] }
ratatui = "0.30.2"
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "sync"] }
tokio-serial = "5.5.0"
toml = "1.1.4"
