name: benchmark

on:
  workflow_call:
  workflow_dispatch:
jobs:
  cargo-bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false
      - uses: ./.github/actions/rust/cargo-bench
        with:
          working-directory: ./rust
          args: -p pyxis

  pytest-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
      - run: pixi run maturin develop --profile release
        shell: pwsh
        working-directory: ./python
      - name: Run benchmarks
        uses: CodSpeedHQ/action@281164b0f014a4e7badd2c02cecad9b595b70537 # v4.11.1
        env:
          PYTHONPATH: ./
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pixi run -e bench pytest ./benches --codspeed
          mode: simulation
          working-directory: ./python
