name: benchmark

on:
  workflow_call:
  workflow_dispatch:
jobs:
  cargo-bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          run-install: false
      - uses: ./.github/actions/rust/cargo-bench
        with:
          working-directory: ./rust
          args: -p pyxis

  pytest-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          run-install: false

      - run: pixi run maturin develop --profile release
        shell: pwsh
        working-directory: ./python

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        env:
          PYTHONPATH: ./
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pixi run -e bench pytest ./benches --codspeed
          mode: simulation
          working-directory: ./python
