name: benchmark

on:
  pull_request:
    types:
      - edited
      - synchronize
      - labeled

  push:
    branches: [main]

permissions: read-all

jobs:
  cargo-bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-codspeed --locked

      - name: Build the benchmark target(s)
        run: cargo codspeed build -p pyxis
        working-directory: ./rust

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          run: cargo codspeed run
          mode: walltime
          token: ${{ secrets.CODSPEED_TOKEN }}
          working-directory: ./rust
  pytest-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          run-install: false

      - run: ./python/scripts/maturin-develop.ps1 -config release
        shell: pwsh

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        env:
          PYTHONPATH: ./
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pixi run -e bench pytest ./benches --codspeed
          mode: walltime
          working-directory: ./python
