name: changelog

on:
    workflow_dispatch:
    issue_comment:
        types: [created,edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'update changelog')
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/pull-request-comment-branch@v3
        id: comment-branch

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false
      - run: pixi global install git-cliff

      - run: echo git-cliff > changelog.md

      - run: |
          try
          {
            git config user.name  "Glatzel"
            git config user.email "chenzelin9794@gmail.com"
            git add changelog.md
            git commit -m "chore: update changelog.md"
            git push
          }catch{}
        shell: pwsh
