name: cpp

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
permissions: read-all
env:
  CPP_ROOT: ./cpp
jobs:
  build-cpp:
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest,macos-latest]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v4
      - name: build cpp
        run: ${{env.CPP_ROOT}}/scripts/build-cpp.ps1 ${{ inputs.release && '-config release' || null }}
        shell: pwsh
