name: cpp-CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
permissions: read-all
env:
  CPP_ROOT: ./cpp
jobs:
  build-cpp:
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v4
      - name: build cpp
        run: ${{env.CPP_ROOT}}/scripts/build-cpp.ps1 ${{ inputs.release && '-config release' || null }}
        shell: pwsh

      - name: upload cpp
        if: ${{inputs.release}}
        uses: actions/upload-artifact@v4
        with:
          name: pyxis-cpp-${{matrix.machine}}
          path: ${{env.CPP_ROOT}}/dist/*.7z
          if-no-files-found: error
