name: csharp-CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
env:
  CSHARP_ROOT: ./csharp
jobs:
  build-csharp:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: build
        if: ${{!inputs.release}}
        run: ${{env.CSHARP_ROOT}}/scripts/build.ps1 -config ${{ inputs.release && 'Release' || 'Debug' }}

      - name: test
        if: ${{!inputs.release}}
        run: ${{env.CSHARP_ROOT}}/scripts/test.ps1

      - name: Upload cov results to Codecov
        if: ${{ !cancelled() && !inputs.release}}
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() && !inputs.release}}
        uses: codecov/test-results-action@v1
        with:
          files: ./tests/*/TestResults/TestResults.xml
          fail_ci_if_error: true

      - name: pack
        if: ${{inputs.release}}
        run: ${{env.CSHARP_ROOT}}/scripts/pack.ps1 -config ${{ inputs.release && 'Release' || 'Debug' }}
      - name: upload nupkg
        uses: actions/upload-artifact@v4
        with:
          name: pyxis-csharp
          path: |
            ${{env.CSHARP_ROOT}}/dist/*.nupkg
          if-no-files-found: error
