name: cpp

on:
  workflow_call:
  workflow_dispatch:
permissions: read-all
env:
  CPP_ROOT: ./cpp
jobs:
  build-cpp:
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, macos-latest,ubuntu-24.04-arm]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v4
      - name: build cpp
        run: ${{env.CPP_ROOT}}/scripts/build-cpp.ps1
        shell: pwsh
