name: cuda-CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      build-release:
        type: boolean
        default: false
env:
  CUDA_ROOT: ./cuda
jobs:
  # region cuda
  build-cuda:
    strategy:
      fail-fast: false
      matrix:
        include:
          - machine: windows-latest
            sub-packages: '["nvcc","cudart"]'
          - machine: ubuntu-latest
            sub-packages: '["nvcc"]'
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v4
      - uses: Jimver/cuda-toolkit@v0.2.22
        with:
          cuda: "12.8.0"
          sub-packages: ${{matrix.sub-packages}}
          method: network
      - name: build cuda
        run: ${{env.CUDA_ROOT}}/scripts/build-cuda.ps1
        shell: pwsh
      - name: upload cuda
        uses: actions/upload-artifact@v4
        with:
          name: pyxis-cuda-${{matrix.machine}}
          path: ${{env.CUDA_ROOT}}/dist/*.7z
          if-no-files-found: error
