name: cuda-CI
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
permissions: read-all
env:
  CUDA_ROOT: ./cuda
jobs:
  # region cuda
  build-cuda:
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest,ubuntu-latest]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v4

      - name: build cuda
        run: ${{env.CUDA_ROOT}}/scripts/build-cuda.ps1
        shell: pwsh

      - name: upload cuda
        if: ${{inputs.release}}
        uses: actions/upload-artifact@v4
        with:
          name: pyxis-cuda-${{matrix.machine}}
          path: ${{env.CUDA_ROOT}}/dist/*.7z
          if-no-files-found: error
