name: python-CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
      event:
        type: string
        required: true
permissions: read-all
env:
  PYTHON_CUDA_ROOT: ${{github.workspace}}/python-cuda
jobs:
  check-test:
    if: ${{inputs.event == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: change
        uses: tj-actions/changed-files@v46
        with:
          files: |
            ${{!env.PYTHON_CUDA_ROOT}}/junit.xml
            ${{!env.PYTHON_CUDA_ROOT}}/coverage.xml
      - if: ${{steps.change.outputs.all_modified  != 'true'}}
        run: |
          echo "::error title=Test Report Outdated::Run test on local machine and update the test report."
          exit 1

  rattler-build:
    env:
      PYTEST_ADDOPTS: "--color=yes"
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest]
        include:
          - machine: windows-latest
            os: win-64
          - machine: ubuntu-latest
            os: linux-64

    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          run-install: false

      - name: build
        run: ${{env.PYTHON_CUDA_ROOT}}/rattler/ci-pyxis-cuda-py.ps1 ${{ inputs.release && '-config  release' || null }}
        shell: pwsh

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: pyxis-cuda-python-${{matrix.machine}}
          path: |
            ${{env.PYTHON_CUDA_ROOT}}/rattler/output/${{matrix.os}}/*.conda
          if-no-files-found: error


  upload-cov:
    if: ${{!inputs.release}}
    strategy:
      fail-fast: false
      matrix:
        machine: [ windows-latest, ubuntu-latest]
    runs-on: ${{matrix.machine}}
    steps:
       - uses: actions/checkout@v4
       - name: Upload results to Codecov
         if: ${{ !cancelled() }}
         uses: codecov/codecov-action@v5
       - name: Upload test results to Codecov
         if: ${{ !cancelled()}}
         uses: codecov/test-results-action@v1
         with:
           fail_ci_if_error: true
           token: ${{ secrets.CODECOV_TOKEN }}
