name: python

on:
  workflow_dispatch:
  workflow_call:
permissions: read-all
env:
  WORKDIR: ./python
defaults:
  run:
    working-directory: ./python
jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
      - name: sphinx build
        run: ./scripts/sphinx.ps1
        shell: pwsh

  rattler-build:
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, ubuntu-24.04-arm]
        include:
          - machine: windows-latest
          - machine: ubuntu-latest
          - machine: macos-latest

    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust

      - name: build and test
        run: |
          ./scripts/maturin-develop.ps1
          ./scripts/pytest.ps1
        shell: pwsh

      - name: Upload results to Codecov
        if: ${{ !cancelled()}}
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          report_type: test_results
          fail_ci_if_error: true
  cargo-clippy:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: ./.github/actions/rust/cargo-clippy
        with:
          working-directory: ${{env.WORKDIR}}
