name: rust

on:
  workflow_dispatch:
  workflow_call:

permissions: read-all

env:
  WORKDIR: ./rust
defaults:
  run:
    working-directory: ./rust
jobs:
  cargo-test:
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v6
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          run-install: false
      - uses: dtolnay/rust-toolchain@nightly
      - uses: ./.github/actions/cargo-test
        with:
          working-directory: ${{env.WORKDIR}}
  cargo-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          run-install: false
      - uses: dtolnay/rust-toolchain@nightly
      - uses: ./.github/actions/cargo-doc
        with:
          working-directory: ${{env.WORKDIR}}
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          run-install: false
      - uses: dtolnay/rust-toolchain@nightly
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: ./.github/actions/cargo-clippy
        with:
          working-directory: ${{env.WORKDIR}}
