name: rust-CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false

permissions: read-all

env:
  RUST_CUDA_ROOT: ./rust-cuda

jobs:
  build-rust-cuda:
    if: ${{!inputs.release}}
    strategy:
      fail-fast: false
      matrix:
        machine: [ windows-latest, ubuntu-latest]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        if: ${{runner.os == 'Windows'}}
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          run-install: false
      - uses: dtolnay/rust-toolchain@stable
      - name: build cuda
        run: ${{env.RUST_CUDA_ROOT}}/scripts/build-rust-cuda.ps1
        shell: pwsh
