name: rust-cuda

on:
  workflow_dispatch:
  workflow_call:

permissions: read-all

env:
  RUST_CUDA_ROOT: ./rust-cuda

jobs:
  cargo-test:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - run: ${{env.RUST_CUDA_ROOT}}/scripts/cargo-test.ps1
      - name: Upload results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
      - name: Upload test results to Codecov
        if: ${{ !cancelled()}}
        uses: codecov/test-results-action@v1
        with:
          fail_ci_if_error: true

  build-rust-cuda:
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest]
    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        if: ${{runner.os == 'Windows'}}
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          run-install: false
      - uses: dtolnay/rust-toolchain@stable
      - name: build cuda
        run: ${{env.RUST_CUDA_ROOT}}/scripts/build-rust-cuda.ps1
        shell: pwsh
