name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  schedule:
    - cron: 0 16 * * *

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
  changed:
    outputs:
      changed-benchmark: ${{steps.main.outputs.benchmark_any_changed}}
      changed-python: ${{steps.main.outputs.python_any_changed}}
      changed-rust: ${{steps.main.outputs.rust_any_changed}}

    runs-on: ubuntu-latest
    steps:
      - if: ${{github.event_name == 'pull_request' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: main
        if: ${{github.event_name == 'pull_request'}}
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files_yaml: |
            benchmark:
              - ./.github/workflows/benchmark.yml
              - ./python/**
              - ./rust/**
            python:
              - ./.github/actions/rust/**
              - ./.github/workflows/ci-python.yml
              - ./python/**
            rust:
              - ./.github/actions/rust/**
              - ./.github/workflows/ci-rust.yml
              - ./rust/**

  python:
    needs: changed
    if: ${{ needs.changed.outputs.changed-python != 'false' }}
    env:
      WORKDIR: ./python
    defaults:
      run:
        working-directory: ./python
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, ubuntu-24.04-arm]
        include:
          - machine: windows-latest
          - machine: ubuntu-latest
          - machine: macos-latest

    runs-on: ${{matrix.machine}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
        with:
          components: ${{ matrix.machine == 'ubuntu-latest' && 'clippy' || null }}
      - uses: ./.github/actions/rust/cargo-clippy
        if: ${{ matrix.machine != 'ubuntu-latest' }}
        with:
          working-directory: ${{env.WORKDIR}}
      - name: sphinx build
        if: ${{ matrix.machine != 'ubuntu-latest' }}
        run: ./scripts/sphinx.ps1
        shell: pwsh
      - name: build and test
        run: |
          ./scripts/maturin-develop.ps1
          ./scripts/pytest.ps1
        shell: pwsh

      - uses: ./.github/actions/common/codecov
        if: ${{!cancelled()}}

  rust:
    needs: changed
    if: ${{ needs.changed.outputs.changed-rust != 'false' }}
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.machine }}
    env:
      WORKDIR: ./rust
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: nightly
          components: ${{ matrix.machine == 'ubuntu-latest' && 'clippy' || null }}
      - uses: ./.github/actions/rust/cargo-clippy
        if: ${{ matrix.machine == 'ubuntu-latest' }}
        with:
          working-directory: ${{env.WORKDIR}}
      - uses: ./.github/actions/rust/cargo-doc
        if: ${{ matrix.machine == 'ubuntu-latest' }}
        with:
          working-directory: ${{env.WORKDIR}}
      - uses: ./.github/actions/rust/cargo-test
        with:
          working-directory: ${{env.WORKDIR}}
          global-args: --workspace --all-features
      - uses: ./.github/actions/common/codecov
        if: ${{!cancelled()}}

  benchmark:
    needs: changed
    if: ${{ needs.changed.outputs.changed-benchmark != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
      #rust
      - uses: ./.github/actions/rust/cargo-bench
        with:
          working-directory: ./rust
          args: -p pyxis
      # python
      - run: pixi run maturin develop --profile release
        shell: pwsh
        working-directory: ./python
      - name: Run benchmarks
        uses: CodSpeedHQ/action@1c8ae4843586d3ba879736b7f6b7b0c990757fab # v4.12.1
        env:
          PYTHONPATH: ./
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pixi run -e bench pytest ./benches --codspeed
          mode: simulation
          working-directory: ./python
  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [lefthook, changed, python, rust, benchmark]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
