name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  schedule:
    - cron: 0 16 * * *

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/ci-lefthook.yml
  changed:
    outputs:
      changed-benchmark: ${{steps.main.outputs.benchmark_any_changed}}
      changed-python: ${{steps.main.outputs.python_any_changed}}
      changed-rust: ${{steps.main.outputs.rust_any_changed}}

    runs-on: ubuntu-latest
    steps:
      - if: ${{github.event_name == 'pull_request' }}
        uses: actions/checkout@v6
      - id: main
        if: ${{github.event_name == 'pull_request'}}
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            benchmark:
              - ./.github/workflows/benchmark.yml
              - ./python/**
              - ./rust/**
            python:
              - ./.github/workflows/ci-python.yml
              - ./python/**
            rust:
              - ./.github/workflows/ci-rust.yml
              - ./rust/**

  python:
    needs: changed
    if: ${{ needs.changed.outputs.changed-python != 'false' }}
    uses: ./.github/workflows/ci-python.yml

  rust:
    needs: changed
    if: ${{ needs.changed.outputs.changed-rust != 'false' }}
    uses: ./.github/workflows/rust.yml
    with:
      doc: true
      test: true
      test-machine: "['windows-latest', 'ubuntu-latest', 'macos-latest', 'ubuntu-24.04-arm']"
  benchmark:
    needs: changed
    if: ${{ needs.changed.outputs.changed-benchmark != 'false' }}
    uses: ./.github/workflows/benchmark.yml
  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs: [lefthook, changed, python, rust, benchmark]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
