name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  schedule:
    - cron: 0 16 * * *

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
      pull-requests: write
  changed:
    outputs:
      changed-benchmark: ${{steps.main.outputs.benchmark_any_changed}}
      changed-python: ${{steps.main.outputs.python_any_changed}}
      changed-rust: ${{steps.main.outputs.rust_any_changed}}
      changed-tool-gnss-receiver: ${{steps.main.outputs.tool-gnss-receiver_any_changed}}
      changed-tool-pyxis-cli: ${{steps.main.outputs.tool-pyxis-cli_any_changed}}

    runs-on: ubuntu-latest
    steps:
      - if: ${{github.event_name == 'pull_request' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: main
        if: ${{github.event_name == 'pull_request'}}
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files_yaml: |
            benchmark:
              - ./python/**
              - ./rust/**
            python:
              - ./.github/workflows/ci-python.yml
              - ./python/**
            rust:
              - ./.github/workflows/ci-rust.yml
              - ./rust/**
            tool-gnss-receiver:
              - ./tools/gnss-receiver/**
              - ./rust/**
            tool-pyxis-cli:
              - ./tools/pyxis-cli/**
              - ./rust/**

  python:
    needs: changed
    if: ${{ needs.changed.outputs.changed-python != 'false' }}
    env:
      WORKDIR: ./python
    defaults:
      run:
        working-directory: ./python
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, ubuntu-26.04-arm]
        include:
          - machine: windows-latest
          - machine: ubuntu-latest
          - machine: macos-latest

    runs-on: ${{matrix.machine}}
    steps:
      - parallel:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          - uses: Glatzel/template/.github/actions/rust/setup-rust@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
            with:
              components: ${{ matrix.machine == 'ubuntu-latest' && 'clippy' || null }}
      - uses: Glatzel/template/.github/actions/rust/cargo-clippy@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        if: ${{ matrix.machine == 'ubuntu-latest' }}
        with:
          working-directory: ${{env.WORKDIR}}
      - name: build
        run: |
          ./scripts/maturin-develop.ps1
        shell: pwsh
      - uses: Glatzel/template/.github/actions/python/pytest@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        with:
          working-directory: ./python
      - uses: Glatzel/template/.github/actions/common/codecov@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        if: ${{!cancelled()}}

  rust:
    needs: changed
    if: ${{ needs.changed.outputs.changed-rust != 'false' }}
    strategy:
      fail-fast: false
      matrix:
        machine: [windows-latest, ubuntu-latest, macos-latest, ubuntu-26.04-arm]
    runs-on: ${{ matrix.machine }}
    env:
      WORKDIR: ./rust
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}
    steps:
      - parallel:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            with:
              submodules: true
          - uses: Glatzel/template/.github/actions/rust/setup-rust@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
            with:
              toolchain: nightly
              components: ${{ matrix.machine == 'ubuntu-latest' && 'clippy' || null }}
      - uses: Glatzel/template/.github/actions/rust/cargo-clippy@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        if: ${{ matrix.machine == 'ubuntu-latest' }}
        with:
          working-directory: ${{env.WORKDIR}}
      - uses: Glatzel/template/.github/actions/rust/cargo-doc@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        if: ${{ matrix.machine == 'ubuntu-latest' }}
        with:
          working-directory: ${{env.WORKDIR}}
      - uses: Glatzel/template/.github/actions/rust/cargo-test@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        with:
          working-directory: ${{env.WORKDIR}}
          global-options: --workspace --all-features
      - uses: Glatzel/template/.github/actions/common/codecov@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        if: ${{!cancelled()}}

  tool-gnss-receiver:
    needs: changed
    if: ${{ needs.changed.outputs.changed-tool-gnss-receiver != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - parallel:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          - uses: Glatzel/template/.github/actions/rust/setup-rust@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
            with:
              # toolchain: nightly
              components: clippy
      - uses: Glatzel/template/.github/actions/rust/cargo-clippy@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        with:
          working-directory: ./tools/gnss-receiver
      # - uses: Glatzel/template/.github/actions/rust/cargo-test
      #   with:
      #     working-directory: ./tools/gnss-receiver
      # - uses: Glatzel/template/.github/actions/common/codecov
      #   if: ${{!cancelled()}}

  tool-pyxis-cli:
    needs: changed
    if: ${{ needs.changed.outputs.changed-tool-pyxis-cli != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - parallel:
          - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          - uses: Glatzel/template/.github/actions/rust/setup-rust@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
            with:
              toolchain: nightly
              components: clippy
      - uses: Glatzel/template/.github/actions/rust/cargo-clippy@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        with:
          working-directory: ./tools/pyxis-cli
      - uses: Glatzel/template/.github/actions/rust/cargo-test@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        with:
          working-directory: ./tools/pyxis-cli
      - uses: Glatzel/template/.github/actions/common/codecov@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        if: ${{!cancelled()}}

  benchmark:
    needs: changed
    if: ${{ needs.changed.outputs.changed-benchmark != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - parallel:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - uses: Glatzel/template/.github/actions/rust/setup-rust@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
      #rust
      - uses: Glatzel/template/.github/actions/rust/cargo-bench@12f2e09e2f6e0eb8a65962709e52ab596e672732 # v2026.8.28
        with:
          working-directory: ./rust
          options: -p pyxis
      # python
      - run: pixi run maturin develop --profile release
        shell: pwsh
        working-directory: ./python
      - name: Run benchmarks
        uses: CodSpeedHQ/action@4296e51e7041e24dadb86d1d6e8b9320d223dbe8 # v5.0.3
        env:
          PYTHONPATH: ./
        with:
          run: pixi run -e bench pytest ./benches --codspeed
          mode: simulation
          working-directory: ./python
  check-point:
    if: ( cancelled() || failure() ) && github.event_name == 'pull_request'
    needs:
      [
        lefthook,
        benchmark,
        changed,
        python,
        rust,
        tool-gnss-receiver,
        tool-pyxis-cli,
      ]
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
