name: Csharp-CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      build-release:
        type: boolean
        default: false
env:
  CSHARP_ROOT: ./csharp
jobs:
  build-csharp:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - id: changed
        if: ${{github.event_name == 'pull_request'}}
        uses: tj-actions/changed-files@v45
        with:
          files: |
            ${{env.CSHARP_ROOT}}/**
      - name: Add msbuild to PATH
        if: ${{ steps.changed.outputs.any_changed != 'false' }}
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: build
        if: ${{ steps.changed.outputs.any_changed != 'false' }}
        run: dotnet build
        working-directory: ${{env.CSHARP_ROOT}}
      - name: test
        if: ${{ steps.changed.outputs.any_changed != 'false' }}
        run: dotnet test --no-build --logger:junit --collect:"XPlat Code Coverage"
        working-directory: ${{env.CSHARP_ROOT}}
      - name: Upload cov results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: ./tests/*/TestResults/TestResults.xml
          fail_ci_if_error: true