name: gpu-test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4

      - run: ./rust-cuda/scripts/update-test-report.ps1
        shell: pwsh

      - run: |
          ./python-cuda/scripts/build-cuda.ps1
          ./python-cuda/scripts/pytest.ps1
        shell: pwsh

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update test reports" || echo "No changes to commit"
          git push
