name: proj-bindgen
on:
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: proj-bindgen-${{ github.ref }}
  cancel-in-progress: false
jobs:
  proj-bindings:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - parallel:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - uses: Glatzel/template/.github/actions/rust/setup-rust@ad33a0f240851891ccb1498fa5d520aafbec454d # v2026.9.11
      - name: proj-bindings
        run: ./rust/scripts/proj-bindings.ps1
        shell: pwsh
      - name: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin ${{ github.ref_name }}
          git add rust/crates/proj-sys/src/bindings.rs
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update libraw bindings"
          git push
        shell: bash
