name: proj-bindgen
on:
    workflow_dispatch:
env:
  RUST_ROOT: ./rust
jobs:
    proj-bindings:
        strategy:
          fail-fast: false
          matrix:
            machine: [windows-latest, ubuntu-latest]
            include:
              - machine: windows-latest
                os: win
              - machine: ubuntu-latest
                os: linux
        runs-on: ${{matrix.machine}}
        env:
          RUSTFLAGS: "-Dwarnings"
        steps:
          - uses: actions/checkout@v4
          - name: Set up pixi
            uses: prefix-dev/setup-pixi@v0.8.8
            with:
              run-install: false
          - uses: dtolnay/rust-toolchain@stable
          - name: proj-bindings
            run: |
              ${{env.RUST_ROOT}}/scripts/proj-bindings.ps1
            shell: pwsh
          - name: upload
            uses: actions/upload-artifact@v4
            with:
              name: proj-bindings-${{matrix.os}}
              path: |
                rust/crates/proj-sys/src/bindings-${{matrix.os}}.rs
              if-no-files-found: error
