name: proj-bindgen
on:
  workflow_dispatch:
env:
  RUST_ROOT: ./rust
permissions:
  contents: read
jobs:
  proj-bindings:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/rust/setup-rust
      - name: proj-bindings
        run: |
          ${{env.RUST_ROOT}}/scripts/proj-bindings.ps1
        shell: pwsh
      - name: upload
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: proj-bindings
          path: |
            rust/crates/proj-sys/src/bindings.rs
          if-no-files-found: error
