name: proj-bindgen
on:
  workflow_dispatch:
env:
  RUST_ROOT: ./rust
permissions:
  contents: read
jobs:
  proj-bindings:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v5
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          run-install: false
      - uses: dtolnay/rust-toolchain@stable
      - name: proj-bindings
        run: |
          ${{env.RUST_ROOT}}/scripts/proj-bindings.ps1
        shell: pwsh
      - name: upload
        uses: actions/upload-artifact@v5
        with:
          name: proj-bindings
          path: |
            rust/crates/proj-sys/src/bindings.rs
          if-no-files-found: error
