name: update-pixi-lockfile
permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * 0

jobs:
  pixi-update:
    uses: Glatzel/template/.github/workflows/update-pixi-lock.yml@main
    with:
      draft: 'true'
