name: update-dependency
permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 1 * *

jobs:
  update-vcpkg-baseline:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./rust/vcpkg/vcpkg-update-baseline.ps1
        shell: pwsh
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "build: update vcpkg baseline"
          title: "build: update vcpkg baseline"
          branch: update-vcpkg-baseline
          base: main
          labels: action
          delete-branch: true
          assignees: Glatzel
          draft: true
